services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app_network

networks:
  app_network: